package com.barasa.speedy.auth.web;

// Entry Point

// Exposes the /api/auth/login endpoint. It receives the username/password DTO and returns the JWT generated by the AuthService.

import com.barasa.speedy.auth.domain.AuthService;
import com.barasa.speedy.auth.web.dto.LoginRequest;
import com.barasa.speedy.auth.web.dto.AuthResponse;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import jakarta.validation.Valid;

@RestController
@RequestMapping("/v1/auth")
@RequiredArgsConstructor
public class AuthRestController {

    private final AuthService authService;

    @PostMapping("/login")
    public ResponseEntity<AuthResponse> authenticateUser(@Valid @RequestBody LoginRequest loginRequest) {

        // 1. Delegate core login and token generation to the domain service
        AuthResponse response = authService.authenticateAndGenerateToken(
                loginRequest.getIdentifier(),
                loginRequest.getPassword());

        // 2. Return the JWT to the client
        return ResponseEntity.ok(response);
    }

    // Additional endpoints like /register or /logout could be added here.
}
