package com.barasa.speedy.auth.web;

// Entry Point
// Exposes the /api/auth/login endpoint. It receives the username/password DTO and returns the JWT generated by the AuthService.
public class AuthController {

}
